In [1]:
#create a class employee and then do the following
class Employee:
     empcount=0
     salsum=0
     def __init__(self,name,family,salary,department):
         self.name=name
         self.family=family
         self.salary=salary
         self.department=department
         Employee.empcount+=1
         Employee.salsum+=self.salary
     def avg(self):
        return Employee.salsum/Employee.empcount
     def displaycount(self):
        print("Total number of employess %d" % Employee.empcount)
     def displayemployee(self):
        print("Name:",self.name,"family:",self.family,"salary:",self.salary,"department",self.department)

emp1=Employee("Nikhil","Kethireddy",5000,"Velosio")
emp2=Employee("Pavan","Kommidi",5600,"Google")
emp3=Employee("Pranay","Chittireddy",6000,"IBM")
print("average:",emp1.avg())

class fulltimeemployee(Employee):
    def __init__(self,name,family,salary,department,c_name):
        super().__init__(name,family,salary,department)
        self.c_name=c_name
    def setcompany(self,c_name):
        self.c_name=c_name
    def getcompany(self):
        if self.c_name not in self.c_name:
            return ""
        return self.c_name
nik=fulltimeemployee("Rahul","Kandakatala",4000,"development","TCS")
nik.setcompany("HP")
nik.getcompany(),nik.displayemployee(),emp1.displaycount()


average: 5533.333333333333
Name: Rahul family: Kandakatala salary: 4000 department development
Total number of employess 4


('HP', None, None)

In [3]:
#using numpy create random vector of size 20 having only float in the range 1-20

import numpy as np
vector=np.arange(1,21,dtype=float)
print(vector)
vector=vector.reshape(4,5)
print(vector)
vector=np.where(np.isin(vector,vector.max(axis=1)),0,vector)
vector

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


array([[ 1.,  2.,  3.,  4.,  0.],
       [ 6.,  7.,  8.,  9.,  0.],
       [11., 12., 13., 14.,  0.],
       [16., 17., 18., 19.,  0.]])